import os

STARTING_ASTEROID_COUNT = 5
EVENT_CARD_SCALE = 0.8
SELECT_CARD_SCALE = 0.15
OFFSCREEN_SPACE = 300
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
SCREEN_TITLE = "Trixter"
HORIZONTAL_CARDS_PADDING = 0.3
DATABASE_FILEPATH = os.path.join("..", "GameData", "GameData.json")
DECISIONS_COUNT = 4
